# Example: Add PBOM lineage tracking to your CI workflow
#
# This workflow shows how to integrate PBOM into an existing CI pipeline.
# The PBOM is generated after your build completes, capturing the exact
# source, build environment, and trigger context.
#
# Place this file at: .github/workflows/ci.yml (or add the steps to your existing workflow)

name: CI with PBOM

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # --- Your existing build steps ---
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: go build -o bin/myapp ./cmd/myapp

      - name: Test
        run: go test ./...

      # --- PBOM lineage tracking ---

      # Step 1: Install the PBOM CLI
      - name: Install PBOM
        run: |
          go install github.com/pbom-dev/pbom/cmd/pbom@main

      # Step 2: Generate a PBOM after your build succeeds
      # The CLI reads GITHUB_* environment variables automatically.
      # No configuration needed.
      - name: Generate PBOM
        run: pbom generate -o ${{ runner.temp }}/pbom.json

      # Step 3: (Optional) Print the lineage summary for visibility in logs
      - name: Inspect PBOM
        run: pbom inspect ${{ runner.temp }}/pbom.json

      # Step 4: Upload the PBOM as a build artifact
      # This preserves the lineage document for later inspection or audit.
      - name: Upload PBOM
        uses: actions/upload-artifact@v4
        with:
          name: pbom-${{ github.run_id }}
          path: ${{ runner.temp }}/pbom.json
          retention-days: 90
          if-no-files-found: warn

      # Step 5: (Future) Push PBOM to OCI registry as a referrer
      # This links the PBOM to the container image it describes.
      # Requires: pbom push implementation + ARTIFACT_DIGEST from your build.
      #
      # - name: Push PBOM to registry
      #   run: |
      #     pbom push ${{ runner.temp }}/pbom.json \
      #       ghcr.io/${{ github.repository }}@${{ env.ARTIFACT_DIGEST }}
